### ISSUE TITLE
PvP cooldown - temporarily disable pvp for player after X kills

### ISSUE THREAD

**Issue by sudokou** [ChanceSD/PvPManager-Issues#165]
**Is your feature request related to a problem? Please describe.**
To prevent pvp abuse we'd like to be able to temporarily disable pvp for a player after they kill X players within Y amount of time.

**Describe the solution you'd like**
```
pvp_cooldown:
    max_kills: 5
    within_time: 5m
    results_in_cooldown: 30m
```
